# Generated by Django 3.2.5 on 2021-10-01 17:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estimated_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Filenames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_data_filename', models.CharField(max_length=50, null=True)),
                ('site_metadata_filename', models.CharField(max_length=50, null=True)),
                ('estimated_data_filename', models.CharField(max_length=50, null=True)),
                ('region_metadata_filename', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('extra_data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(db_index=True, max_length=50, null=True)),
                ('extra_data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estimated_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(db_index=True, max_length=30)),
                ('value', models.FloatField(null=True)),
                ('extra_data', models.JSONField(null=True)),
                ('estimated_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine_the_gap.estimated_data')),
            ],
        ),
        migrations.AddField(
            model_name='estimated_data',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine_the_gap.region'),
        ),
        migrations.CreateModel(
            name='Actual_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(db_index=True, max_length=30)),
                ('value', models.FloatField(null=True)),
                ('actual_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine_the_gap.actual_data')),
            ],
        ),
        migrations.AddField(
            model_name='actual_data',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine_the_gap.sensor'),
        ),
    ]
