# Generated by Django 2.0.13 on 2019-10-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0007_auto_20191026_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_data',
            name='metadata',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
