# Generated by Django 2.0.13 on 2019-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0009_auto_20191026_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_data',
            name='metadata',
            field=models.CharField(max_length=200000, null=True),
        ),
    ]
