# Generated by Django 2.0.13 on 2019-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0010_auto_20191026_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_data',
            name='metadata',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
