# Generated by Django 2.0.13 on 2019-10-28 09:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0011_auto_20191026_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_data',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='actual_data',
            name='long',
        ),
        migrations.AddField(
            model_name='actual_data',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
