# Generated by Django 2.0.13 on 2019-10-28 12:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0012_auto_20191028_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('name', models.CharField(max_length=50)),
                ('metadata', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='actual_data',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='actual_data',
            name='name',
        ),
    ]
