# Generated by Django 2.0.13 on 2019-10-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0013_auto_20191028_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actual_sensor',
            new_name='Sensor',
        ),
    ]
