# Generated by Django 2.0.13 on 2019-10-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0015_auto_20191028_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual_data',
            old_name='location',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='region_data',
            old_name='polygon',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='location',
            new_name='geom',
        ),
    ]
