# Generated by Django 2.0.13 on 2019-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0016_auto_20191028_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual_data',
            old_name='geom',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='region_data',
            old_name='geom',
            new_name='polygon',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='geom',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
