# Generated by Django 2.0.13 on 2019-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0017_auto_20191029_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual_data',
            old_name='location',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='region_data',
            old_name='polygon',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='location',
            new_name='geom',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
