# Generated by Django 2.0.13 on 2019-10-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0018_auto_20191029_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimated_data',
            old_name='metadata',
            new_name='extra_data',
        ),
        migrations.RenameField(
            model_name='region_data',
            old_name='metadata',
            new_name='extra_data',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='metadata',
            new_name='extra_data',
        ),
    ]
