# Generated by Django 2.0.13 on 2019-10-29 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0019_auto_20191029_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_data',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(max_length=2000, srid=4326),
        ),
    ]
