# Generated by Django 2.0.13 on 2019-10-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0020_auto_20191029_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_data',
            name='geom',
        ),
        migrations.AddField(
            model_name='actual_data',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine_the_gap.Sensor'),
        ),
    ]
