# Generated by Django 2.0.13 on 2019-10-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0021_auto_20191030_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region_data',
            new_name='Region',
        ),
        migrations.RemoveField(
            model_name='estimated_data',
            name='region_label',
        ),
        migrations.AddField(
            model_name='estimated_data',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine_the_gap.Region'),
        ),
    ]
