# Generated by Django 2.0.13 on 2019-10-30 13:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0022_auto_20191030_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_label',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        
        migrations.AlterField(
            model_name='sensor',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=4326),
        ),
    ]
