# Generated by Django 2.0.13 on 2019-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0025_auto_20191030_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated_data',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
