# Generated by Django 2.0.13 on 2019-10-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0027_auto_20191030_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual_data',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='estimated_data',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
