# Generated by Django 2.0.13 on 2019-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0028_auto_20191031_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual_data',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estimated_data',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
    ]
