# Generated by Django 2.0.13 on 2019-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0029_auto_20191031_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filenames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_data_file', models.CharField(max_length=50, null=True)),
                ('sensor_data_file', models.CharField(max_length=50, null=True)),
                ('estimated_data_file', models.CharField(max_length=50, null=True)),
                ('region_data_file', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
