# Generated by Django 2.0.13 on 2019-11-07 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0031_actual_data_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, default=None, srid=4326),
            preserve_default=False,
        ),
    ]
