# Generated by Django 2.0.13 on 2019-11-16 08:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0033_auto_20191111_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(db_index=True, max_length=30)),
                ('value', models.FloatField(null=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='actual_data',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='actual_data',
            name='value',
        ),
        migrations.AddField(
            model_name='actual_value',
            name='actual_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine_the_gap.Actual_data'),
        ),
    ]
