# Generated by Django 2.0.13 on 2019-11-23 10:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0038_auto_20191117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
