# Generated by Django 2.0.13 on 2019-11-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0039_auto_20191123_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_value',
            name='extra_data',
        ),
    ]
