# Generated by Django 2.0.13 on 2019-11-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0040_remove_actual_value_extra_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filenames',
            old_name='actual_data_file',
            new_name='actual_data_filename',
        ),
        migrations.RenameField(
            model_name='filenames',
            old_name='estimated_data_file',
            new_name='estimated_data_filename',
        ),
        migrations.RenameField(
            model_name='filenames',
            old_name='region_data_file',
            new_name='region_data_filename',
        ),
        migrations.RenameField(
            model_name='filenames',
            old_name='sensor_data_file',
            new_name='sensor_data_filename',
        ),
    ]
