# Generated by Django 2.0.13 on 2019-12-06 08:29

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0042_auto_20191125_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region_dynamic',
            fields=[
                ('region_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('estimation_method', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
