# Generated by Django 3.0.5 on 2020-12-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0043_region_dynamic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual_data',
            old_name='sensor',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='filenames',
            old_name='sensor_metadata_filename',
            new_name='site_metadata_filename',
        ),
    ]
