# Generated by Django 3.0.5 on 2020-12-28 19:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0044_auto_20201213_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_value',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
