# Generated by Django 3.0.5 on 2020-12-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0045_actual_value_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_value',
            name='extra_data',
        ),
    ]
