# Generated by Django 3.0.5 on 2021-01-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0046_remove_actual_value_extra_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region_dynamic',
        ),
    ]
