# Generated by Django 3.2.5 on 2021-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_the_gap', '0047_delete_region_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated_value',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
    ]
